import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { QueryClientProvider } from "../../providers/query-client-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="p-4 pt-6 antialiased font-sans"
      >
        <Toaster richColors/>
        <QueryClientProvider>
        {/* <Header /> */}
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
